# Generated by Django 6.0.2 on 2026-02-25 10:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_sku', models.CharField(blank=True, max_length=128, null=True)),
                ('store_name', models.CharField(max_length=512)),
                ('store_brand', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, max_length=2000, null=True)),
                ('image_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('original_unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=64, null=True)),
                ('offer', models.CharField(blank=True, max_length=255, null=True)),
                ('snapshot_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_listings', to='catalog.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='catalog.store')),
            ],
            options={
                'ordering': ['store__name', 'store_name'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('store_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='ingestion.storelisting')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlerRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'running'), ('success', 'success'), ('failed', 'failed'), ('partial', 'partial')], default='running', max_length=16)),
                ('error_summary', models.TextField(blank=True)),
                ('items_seen', models.PositiveIntegerField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawler_runs', to='catalog.store')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['store', '-started_at'], name='idx_run_store_started'), models.Index(fields=['status'], name='idx_run_status')],
                'constraints': [models.CheckConstraint(condition=models.Q(('finished_at__isnull', True), ('finished_at__gte', models.F('started_at')), _connector='OR'), name='ck_run_finished_after_started')],
            },
        ),
        migrations.AddIndex(
            model_name='storelisting',
            index=models.Index(fields=['store', 'is_active'], name='idx_listing_store_active'),
        ),
        migrations.AddIndex(
            model_name='storelisting',
            index=models.Index(fields=['product', 'is_active'], name='idx_listing_product_active'),
        ),
        migrations.AddIndex(
            model_name='storelisting',
            index=models.Index(fields=['store', 'last_seen_at'], name='idx_listing_store_seen'),
        ),
        migrations.AddConstraint(
            model_name='storelisting',
            constraint=models.CheckConstraint(condition=models.Q(('store_name', ''), _negated=True), name='ck_listing_name_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='storelisting',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('store_sku__isnull', False), models.Q(('store_sku', ''), _negated=True)), models.Q(('url__isnull', False), models.Q(('url', ''), _negated=True)), _connector='OR'), name='ck_listing_id_source_present'),
        ),
        migrations.AddConstraint(
            model_name='storelisting',
            constraint=models.CheckConstraint(condition=models.Q(('final_price__gte', 0), ('final_price__isnull', True), _connector='OR'), name='ck_listing_final_price_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='storelisting',
            constraint=models.CheckConstraint(condition=models.Q(('final_unit_price__gte', 0), ('final_unit_price__isnull', True), _connector='OR'), name='ck_listing_final_unit_price_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='storelisting',
            constraint=models.CheckConstraint(condition=models.Q(('original_price__gte', 0), ('original_price__isnull', True), _connector='OR'), name='ck_listing_original_price_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='storelisting',
            constraint=models.CheckConstraint(condition=models.Q(('original_unit_price__gte', 0), ('original_unit_price__isnull', True), _connector='OR'), name='ck_listing_original_unit_price_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='storelisting',
            constraint=models.CheckConstraint(condition=models.Q(('last_seen_at__gte', models.F('snapshot_at'))), name='ck_listing_last_seen_gte_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='storelisting',
            constraint=models.UniqueConstraint(condition=models.Q(('store_sku__isnull', False), models.Q(('store_sku', ''), _negated=True)), fields=('store', 'store_sku'), name='uq_listing_store_sku'),
        ),
        migrations.AddConstraint(
            model_name='storelisting',
            constraint=models.UniqueConstraint(condition=models.Q(('url__isnull', False), models.Q(('url', ''), _negated=True), models.Q(('store_sku__isnull', True), ('store_sku', ''), _connector='OR')), fields=('store', 'url'), name='uq_listing_store_url_no_sku'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['store_listing', '-captured_at'], name='idx_pricehistory_listing_time'),
        ),
        migrations.AddConstraint(
            model_name='pricehistory',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0), ('price__isnull', True), _connector='OR'), name='ck_ph_price_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='pricehistory',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0), ('unit_price__isnull', True), _connector='OR'), name='ck_ph_unit_price_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='pricehistory',
            constraint=models.UniqueConstraint(fields=('store_listing', 'captured_at'), name='uq_pricehistory_listing_captured'),
        ),
    ]
