# Generated by Django 6.0.2 on 2026-02-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storelisting',
            name='source_category',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
    ]
