# Generated by Django 6.0.2 on 2026-03-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_image'),
        ('ingestion', '0002_storelisting_source_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='storelisting',
            name='discount_percent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storelisting',
            name='hidden_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='storelisting',
            name='hidden_unit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='storelisting',
            name='one_plus_one',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storelisting',
            name='promo_text',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='storelisting',
            name='root_category',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storelisting',
            name='two_plus_one',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='storelisting',
            constraint=models.CheckConstraint(condition=models.Q(('hidden_price__gte', 0), ('hidden_price__isnull', True), _connector='OR'), name='ck_listing_hidden_price_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='storelisting',
            constraint=models.CheckConstraint(condition=models.Q(('hidden_unit_price__gte', 0), ('hidden_unit_price__isnull', True), _connector='OR'), name='ck_listing_hidden_unit_price_nonneg'),
        ),
    ]
