# Generated by Django 6.0.2 on 2026-03-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_alter_storelisting_hidden_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storelisting',
            name='final_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
