# Generated by Django 6.0.2 on 2026-03-09 18:10

from django.db import migrations, models


_FALSEY_STRINGS = {"", "0", "false", "no", "n", "none", "null", "nan", "n/a", "-"}


def _parse_offer_flag(value) -> bool:
    if value is None:
        return False
    text = str(value).strip().lower()
    return text not in _FALSEY_STRINGS


def _populate_offer_bool(apps, schema_editor):
    StoreListing = apps.get_model("ingestion", "StoreListing")
    pending = []
    for listing in StoreListing.objects.only("id", "offer").iterator(chunk_size=2000):
        listing.offer_bool = _parse_offer_flag(listing.offer)
        pending.append(listing)
        if len(pending) >= 2000:
            StoreListing.objects.bulk_update(pending, ["offer_bool"], batch_size=2000)
            pending.clear()
    if pending:
        StoreListing.objects.bulk_update(pending, ["offer_bool"], batch_size=2000)


def _restore_offer_text(apps, schema_editor):
    StoreListing = apps.get_model("ingestion", "StoreListing")
    pending = []
    for listing in StoreListing.objects.only("id", "offer_bool").iterator(chunk_size=2000):
        listing.offer = "offer" if listing.offer_bool else None
        pending.append(listing)
        if len(pending) >= 2000:
            StoreListing.objects.bulk_update(pending, ["offer"], batch_size=2000)
            pending.clear()
    if pending:
        StoreListing.objects.bulk_update(pending, ["offer"], batch_size=2000)


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0005_alter_storelisting_final_unit_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="storelisting",
            name="offer_bool",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(_populate_offer_bool, _restore_offer_text),
        migrations.RemoveField(
            model_name="storelisting",
            name="offer",
        ),
        migrations.RenameField(
            model_name="storelisting",
            old_name="offer_bool",
            new_name="offer",
        ),
    ]
