# Generated by Django 6.0.2 on 2026-03-09 19:11

import re
import unicodedata

from django.db import migrations, models


_MULTISPACE_RE = re.compile(r"\s+")
_NON_ALNUM_RE = re.compile(r"[^0-9a-zA-Zα-ωΑ-Ωάέίόύήώϊϋΐΰς\s]", re.UNICODE)
_DIGRAPH_REPLACEMENTS: tuple[tuple[str, str], ...] = (
    ("ου", "ou"),
    ("αι", "ai"),
    ("ει", "ei"),
    ("οι", "oi"),
    ("υι", "yi"),
    ("γγ", "ng"),
    ("γκ", "gk"),
    ("γξ", "nx"),
    ("γχ", "nch"),
    ("τσ", "ts"),
    ("τζ", "tz"),
    ("μπ", "mp"),
    ("ντ", "nt"),
)
_GREEK_TO_LATIN = {
    "α": "a",
    "β": "v",
    "γ": "g",
    "δ": "d",
    "ε": "e",
    "ζ": "z",
    "η": "i",
    "θ": "th",
    "ι": "i",
    "κ": "k",
    "λ": "l",
    "μ": "m",
    "ν": "n",
    "ξ": "x",
    "ο": "o",
    "π": "p",
    "ρ": "r",
    "σ": "s",
    "ς": "s",
    "τ": "t",
    "υ": "y",
    "φ": "f",
    "χ": "ch",
    "ψ": "ps",
    "ω": "o",
}
_LATIN_PHONETIC_REPLACEMENTS: tuple[tuple[str, str], ...] = (
    ("ph", "f"),
    ("ch", "x"),
    ("ou", "u"),
    ("oi", "i"),
    ("ei", "i"),
    ("yi", "i"),
    ("ai", "e"),
    ("ck", "k"),
)


def _strip_accents(value: str) -> str:
    normalized = unicodedata.normalize("NFD", value)
    return "".join(ch for ch in normalized if unicodedata.category(ch) != "Mn")


def _normalize_text(value: str) -> str:
    lowered = _strip_accents((value or "").lower().replace("\xa0", " "))
    collapsed = _NON_ALNUM_RE.sub(" ", lowered)
    return _MULTISPACE_RE.sub(" ", collapsed).strip()


def _transliterate(value: str) -> str:
    text = _normalize_text(value)
    for src, dst in _DIGRAPH_REPLACEMENTS:
        text = text.replace(src, dst)
    translated = "".join(_GREEK_TO_LATIN.get(ch, ch) for ch in text)
    return _MULTISPACE_RE.sub(" ", translated).strip()


def _normalize_latin(value: str) -> str:
    text = _normalize_text(value)
    for src, dst in _LATIN_PHONETIC_REPLACEMENTS:
        text = text.replace(src, dst)
    return _MULTISPACE_RE.sub(" ", text).strip()


def _build_search_text(value: str) -> str:
    base = _normalize_text(value)
    if not base:
        return ""

    forms: list[str] = [base]
    latin = _transliterate(base)
    if latin and latin not in forms:
        forms.append(latin)
    phonetic = _normalize_latin(latin)
    if phonetic and phonetic not in forms:
        forms.append(phonetic)
    return " ".join(forms)


def _backfill_listing_search_store_name(apps, schema_editor):
    StoreListing = apps.get_model("ingestion", "StoreListing")
    pending = []
    for listing in StoreListing.objects.only("id", "store_name").iterator(chunk_size=2000):
        listing.search_store_name = _build_search_text(listing.store_name or "")
        pending.append(listing)
        if len(pending) >= 2000:
            StoreListing.objects.bulk_update(pending, ["search_store_name"], batch_size=2000)
            pending.clear()
    if pending:
        StoreListing.objects.bulk_update(pending, ["search_store_name"], batch_size=2000)


def _noop(apps, schema_editor):
    return None


def _create_listing_search_trgm_index(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_listing_search_store_name_trgm
        ON ingestion_storelisting
        USING gin (search_store_name gin_trgm_ops)
        """
    )


def _drop_listing_search_trgm_index(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("DROP INDEX IF EXISTS idx_listing_search_store_name_trgm")


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_search_name"),
        ("ingestion", "0006_storelisting_offer_bool"),
    ]

    operations = [
        migrations.AddField(
            model_name="storelisting",
            name="search_store_name",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.RunPython(_backfill_listing_search_store_name, _noop),
        migrations.RunPython(_create_listing_search_trgm_index, _drop_listing_search_trgm_index),
    ]
