# Generated by Django 6.0.2 on 2026-03-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_category_name_en'),
        ('ingestion', '0007_storelisting_search_store_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='storelisting',
            index=models.Index(fields=['product', 'is_active', 'final_price', 'id'], name='idx_listing_prod_price'),
        ),
        migrations.AddIndex(
            model_name='storelisting',
            index=models.Index(fields=['product', 'is_active', 'hidden_price', 'id'], name='idx_listing_prod_hprice'),
        ),
        migrations.AddIndex(
            model_name='storelisting',
            index=models.Index(fields=['product', 'is_active', 'final_unit_price', 'id'], name='idx_listing_prod_unit'),
        ),
        migrations.AddIndex(
            model_name='storelisting',
            index=models.Index(fields=['product', 'is_active', 'hidden_unit_price', 'id'], name='idx_listing_prod_hunit'),
        ),
    ]
