# Generated by Django 6.0.2 on 2026-02-25 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='ck_category_name_nonempty'), models.CheckConstraint(condition=models.Q(('slug', ''), _negated=True), name='ck_category_slug_nonempty')],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='ck_store_name_nonempty')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(max_length=255)),
                ('brand_normalized', models.CharField(blank=True, max_length=128, null=True)),
                ('quantity_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('quantity_unit', models.CharField(blank=True, choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('temaxio', 'temaxio')], max_length=16, null=True)),
                ('normalized_key', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['canonical_name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('canonical_name', ''), _negated=True), name='ck_product_name_nonempty'), models.CheckConstraint(condition=models.Q(('quantity_value__gt', 0), ('quantity_value__isnull', True), _connector='OR'), name='ck_product_qty_positive'), models.CheckConstraint(condition=models.Q(models.Q(('quantity_value__isnull', True), models.Q(('quantity_unit__isnull', True), ('quantity_unit', ''), _connector='OR')), models.Q(('quantity_value__isnull', False), ('quantity_unit__isnull', False), models.Q(('quantity_unit', ''), _negated=True)), _connector='OR'), name='ck_product_qty_pair'), models.UniqueConstraint(condition=models.Q(('normalized_key__isnull', False), models.Q(('normalized_key', ''), _negated=True)), fields=('normalized_key',), name='uq_product_norm_key_present')],
            },
        ),
    ]
