# Generated by Django 6.0.2 on 2026-02-25 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_slug', models.CharField(max_length=128)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='catalog.category')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_aliases', to='catalog.store')),
            ],
            options={
                'ordering': ['source_slug', 'store__name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('source_slug', ''), _negated=True), name='ck_categoryalias_source_nonempty'), models.UniqueConstraint(fields=('store', 'source_slug'), name='uq_categoryalias_store_source'), models.UniqueConstraint(condition=models.Q(('store__isnull', True)), fields=('source_slug',), name='uq_categoryalias_global_source')],
            },
        ),
    ]
