# Generated by Django 6.0.2 on 2026-02-25 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], db_index=True, default='pending', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('candidate_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_reviews', to='catalog.product')),
                ('store_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_reviews', to='ingestion.storelisting')),
            ],
            options={
                'ordering': ['status', '-score'],
                'indexes': [models.Index(fields=['status', '-score'], name='idx_matchreview_queue')],
                'constraints': [models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 1)), name='ck_matchreview_score_range'), models.UniqueConstraint(fields=('store_listing', 'candidate_product'), name='uq_matchreview_listing_candidate')],
            },
        ),
    ]
