# Generated by Django 6.0.2 on 2026-03-13 13:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_category_name_en'),
        ('comparison', '0001_initial'),
        ('ingestion', '0007_storelisting_search_store_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingProductReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('reassigned', 'reassigned'), ('dismissed', 'dismissed')], db_index=True, default='pending', max_length=16)),
                ('report_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_reported_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reassigned_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_product_reassignments', to='catalog.product')),
                ('reported_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_product_reports', to='catalog.product')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_listing_product_reports', to=settings.AUTH_USER_MODEL)),
                ('store_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_product_reports', to='ingestion.storelisting')),
            ],
            options={
                'ordering': ['status', '-last_reported_at', '-id'],
                'indexes': [models.Index(fields=['status', '-last_reported_at'], name='idx_listingreport_queue'), models.Index(fields=['store_listing', 'status'], name='idx_lpr_listing_status')],
                'constraints': [models.CheckConstraint(condition=models.Q(('report_count__gte', 1)), name='ck_listingreport_count_positive'), models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('store_listing',), name='uq_listingreport_pending_listing')],
            },
        ),
    ]
